name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t medialibraryapp-backend .

      # 4. Ejecutar pruebas (opcional)
      - name: Run tests
        run: |
          docker run medialibraryapp-backend npm test